@Api_HostAddress = http://localhost:5198

POST {{Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "nico1_a_gonzalez@hotmail.com",
  "password": "legolas27",
  "branchId": "d5e05a24-868e-4007-84e4-1580250a4fef"
} 