@Api_HostAddress = http://localhost:5198

POST {{Api_HostAddress}}/employee/getbyid
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTRkMjFhZC1jMTk3LTQwMzYtOWQ5OC1hZDY1Y2FlMDYxODIiLCJlbWFpbCI6Im5pY28xX2FfZ29uemFsZXpAaG90bWFpbC5jb20iLCJleHAiOjE3MDMxMjkwOTIsImlzcyI6Ikx1YnJpY2VudHJvIiwiYXVkIjoiTHVicmljZW50cm8ifQ.2VSo94TQ2hSqsoNwXYyHjslSoU2sTazHmiNpAq6uFsw

{
  "id": "495476f9-7d7c-409a-aff9-2198f5fcebbd"
}