@Api_HostAddress = http://localhost:5198

GET  {{Api_HostAddress}}/role/getallpolicies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6Ik5pY29sYXMgR29uemFsZXoiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg1MTY0MTBmLWUyNmMtNGY5MC1iZjA3LTY4MWRkMDA5M2Q0YiIsImVtYWlsIjoibmljbzFfYV9nb256YWxlekBob3RtYWlsLmNvbSIsIlBvbGljeSI6WyJDaGF0UG9saWN5IiwiU2VydmVyUG9saWN5IiwiQ29tcGFueVBvbGljeSIsIkVtcGxveWVlTW9kaWZpY2F0aW9uc1BvbGljeSJdLCJleHAiOjE3MTA3NTY0NjAsImlzcyI6Ikx1YnJpY2VudHJvIiwiYXVkIjoiTHVicmljZW50cm8ifQ.kL1Sh_ABgbAPSaKF_xF4ET_n1dPHvHcEYLsHT3iHaW0
