@Api_HostAddress = https://localhost:7279

GET {{Api_HostAddress}}/chat/getusers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ik5pY29sYXMgR29uemFsZXoiLCJVc2VySWQiOiI4NTE2NDEwZi1lMjZjLTRmOTAtYmYwNy02ODFkZDAwOTNkNGIiLCJlbWFpbCI6Im5pY28xX2FfZ29uemFsZXpAaG90bWFpbC5jb20iLCJQb2xpY3kiOlsiQ2hhdFBvbGljeSIsIlNlcnZlclBvbGljeSIsIkNvbXBhbnlQb2xpY3kiLCJFbXBsb3llZU1vZGlmaWNhdGlvbnNQb2xpY3kiXSwiZXhwIjoxNzEwNjg3OTg0LCJpc3MiOiJMdWJyaWNlbnRybyIsImF1ZCI6Ikx1YnJpY2VudHJvIn0.FqsZnvsGfgIhBbUX_PbC8DHWkDt0FdAnM_O7t0Dq6lw

